endpoints:
  s_endpoint: "/scratch/hpc-prf-whale/WHALE-data/admin_area/total_skol_clean2.nt"
  t_endpoint: "/scratch/hpc-prf-whale/WHALE-data/college_or_uni/total_skol_clean2.nt"

file_paths:
  template_file: "../data/templates/linking_config.xml"
  config_output_dir: "../../../../../LIMES/configs/admin_area_college_uni"
  linking_output_dir: "../../../../../Alignment/procrustes/limes/admin_area_college_uni"
  cache_dir: "../data/cache"
  class_alignment_template_file: "../data/templates/class_alignment.xml"
  query_path: "../data/queries/query_props_coverage_all.rq"
  limes_jar: "/scratch/hpc-prf-whale/albert/limes_custom/limes_custom/limes-core/target/limes-core-1.8.1-SNAPSHOT-shaded.jar"

logging:
  level: "INFO"
