endpoints:
  s_endpoint: ""
  t_endpoint: ""

file_paths:
  template_file: "../data/templates/linking_config.xml"
  config_output_dir: "../../../../LIMES/configs"
  linking_output_dir: "../../../../Alignment/procrustes/limes"
  cache_dir: "../data/cache"
  class_alignment_template_file: "../data/templates/class_alignment.xml"
  query_path: "../data/queries/query_props_coverage_all.rq"
  limes_jar: "../../../../LIMES/target/limes-core-1.8.1-SNAPSHOT.jar"

logging:
  level: "INFO"
